map_type: costmap

obstacle_range: 1.0
raytrace_range: 1.5
inflation_radius: 0.5

transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /roborock/laser/scan, marking: true, clearing: true}
