map_type: costmap

obstacle_range: 2.0
raytrace_range: 2.5
robot_radius: 0.3
inflation_radius: 0.56

transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /roborock/laser/scan, marking: true, clearing: true}
