map_type: costmap

obstacle_range: 0.7
raytrace_range: 0.8
robot_radius: 0.2
inflation_radius: 0.25

transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /roborock/laser/scan, marking: true, clearing: true}
